version: v1alpha
name: "productaffinity-rm"
layer: user
type: lens
tags:
  - lens
description: This semantic model provides comprehensive insights for product affinity analysis.
lens:
  compute: runnable-default
  # secrets:
  #   - name: bitbucket-cred-ra-rw
  #     allKeys: true
  source:
    type: depot
    # name: miniature
    name: postgresdepotmr
  repo:
    url: https://github.com/RachanaM05/DataOSRepo/
    lensBaseDir: Training/semantic-model/model/
    syncFlags:
      - --ref=main

  api:   # optional
    replicas: 1 # optional
    logLevel: info  # optional
    # envs:
    #   LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 500Mi
  worker: # optional
    replicas: 1 # optional
    logLevel: debug  # optional
    # envs:
    #   LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 500Mi
  router: # optional
    logLevel: info  # optional
    # envs:
    #   LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 500Mi
  # iris:
  #   logLevel: info
  #   resources:
  #     requests:
  #       cpu: 200m
  #       memory: 256Mi
  #     limits:
  #       cpu: 1000m
  #       memory: 1024Mi

  metric:
    logLevel: info








